#Requires -Version 7.4
<#
.SYNOPSIS
    Loads credentials from .env.local into $env: — without ever printing a value.

.DESCRIPTION
    Nothing in this repo reads a token from a file at use time. Tools read $env:.
    This script is the one place that turns a pasted value into an environment
    variable, and it is deliberately boring: read the file, set the variables,
    report names and lengths.

    It never prints, logs or interpolates a value. Not truncated, not a prefix.
    A prefix identifies the token type, and the habit is what kills you the day
    this output lands in a CI log. See docs/skills/secret-hygiene.md.

    TODO(01): when .build.ps1 lands, wire this in as an `Env` task and make every
    task that needs a credential depend on it. The dispatcher does not exist yet,
    so there is nothing to hook into today.

.PARAMETER Path
    The dotenv file to read. Defaults to .env.local at the repo root.

.PARAMETER Require
    Variable names that must be present and non-empty. Throws naming the ones that
    are not. Enforced only when you pass it explicitly — the default value is the
    canonical set for this repo and is what -ListRequired reports, so a plain run
    or a -Check on a freshly copied file does not throw before Jerry has pasted
    anything.

.PARAMETER Check
    Report only. Sets no environment variable.

.PARAMETER ListRequired
    Print the default required variable names, one per line, and exit. This is the
    loader publishing its own contract so .env.example can be tested against it
    rather than against a hand-copied list that drifts.

.EXAMPLE
    pwsh -NoProfile -File scripts/env.ps1 -Check
    Report what .env.local holds, change nothing.

.EXAMPLE
    . ./scripts/env.ps1 -Require GITHUB_TOKEN,TF_VAR_owner
    Load, and fail loudly if either is missing.
#>
[CmdletBinding()]
param(
    [string] $Path,

    [string[]] $Require = @('GITHUB_TOKEN', 'TF_VAR_owner'),

    [switch] $Check,

    [switch] $ListRequired
)

$ErrorActionPreference = 'Stop'
$PSNativeCommandUseErrorActionPreference = $true

# Resolved from THIS FILE's location, not from `git rev-parse --show-toplevel` plus a check
# that the resulting path ends in the repository's name.
#
# The old guard was wrong in both directions. It REJECTED a correct tree whose directory was
# named anything else - a clone into a different folder, a worktree, and in particular the
# container, where the repository is bind-mounted at /work; that threw 'NOT IN IMAGE BUILDER'
# out of twelve in-container tests. And it ACCEPTED any tree at all, as long as someone had
# named the directory after the repository this one was copied from. For a script that goes looking for a file
# of credentials, "the folder has the right name" is not an identity check.
#
# $PSScriptRoot/.. is this script's own repository by construction, whatever the directory is
# called and wherever it is mounted. tests/TestHelpers.psm1 resolves the same way and its
# docstring names this exact case.
$repoRoot = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
if (-not (Test-Path -LiteralPath (Join-Path $repoRoot '.env.example'))) {
    throw "not a claude.agent.images tree: no .env.example at $repoRoot"
}

if ($ListRequired) {
    $Require | Write-Output
    return
}

if (-not $Path) { $Path = Join-Path $repoRoot '.env.local' }
$example = Join-Path $repoRoot '.env.example'

# Create it rather than fail. The whole point is that Jerry copies nothing by hand.
if (-not (Test-Path -LiteralPath $Path)) {
    Write-Verbose "no file at $Path — creating it"
    $header = @(
        '# LOCAL ONLY — gitignored — paste real values here.'
        '# Never commit this file. Never paste its contents into a chat.'
        '# Generated by scripts/env.ps1 from .env.example.'
        ''
    )
    if (Test-Path -LiteralPath $example) {
        Set-Content -LiteralPath $Path -Encoding utf8 -Value ($header + (Get-Content -LiteralPath $example))
    }
    else {
        Set-Content -LiteralPath $Path -Encoding utf8 -Value $header
    }
    Write-Host ("created {0} — paste your values into it" -f (Resolve-Path -LiteralPath $Path -Relative))
}

Write-Verbose "reading $Path"
$lines = Get-Content -LiteralPath $Path

$values = [ordered]@{}
$lineNo = 0
foreach ($line in $lines) {
    $lineNo++
    if ([string]::IsNullOrWhiteSpace($line)) { continue }
    if ($line -match '^\s*#') { continue }

    if ($line -notmatch '^\s*(?<name>[A-Za-z_][A-Za-z0-9_]*)\s*=(?<value>.*)$') {
        Write-Warning ("{0}:{1}: not a NAME=value line, skipped" -f (Split-Path -Leaf $Path), $lineNo)
        continue
    }

    $name = $Matches['name']
    $value = $Matches['value'].Trim()

    # Strip one layer of matching quotes.
    if ($value.Length -ge 2 -and
        (($value[0] -eq '"' -and $value[-1] -eq '"') -or ($value[0] -eq "'" -and $value[-1] -eq "'"))) {
        $value = $value.Substring(1, $value.Length - 2)
    }

    # Expand a leading ~. A literal tilde is not a path any tool can open.
    if ($value -eq '~') { $value = $HOME }
    elseif ($value -match '^~[/\\]') { $value = Join-Path $HOME $value.Substring(2) }

    # Debug prints the NAME only. There is no mode of this script that prints a value.
    Write-Debug ("parsed {0} ({1} chars)" -f $name, $value.Length)
    $values[$name] = $value
}

foreach ($name in $values.Keys) {
    $value = $values[$name]
    if (-not $Check) { Set-Item -Path "env:$name" -Value $value }

    $state = if ([string]::IsNullOrEmpty($value)) { 'EMPTY' } else { "set (len $($value.Length))" }
    Write-Host ('{0,-30} {1}' -f $name, $state)
}

if ($Check) {
    Write-Host ''
    Write-Host ('-Check: reported {0} variable(s), set none.' -f $values.Count)
}

if ($PSBoundParameters.ContainsKey('Require')) {
    $missing = $Require | Where-Object { [string]::IsNullOrEmpty($values[$_]) }
    if ($missing) {
        # Names only. An error message is the easiest place in a program to leak a secret.
        throw ("env.ps1: missing or empty required variable(s): {0}. Paste them into {1}." -f
            ($missing -join ', '), $Path)
    }
    Write-Verbose ("all {0} required variable(s) present" -f $Require.Count)
}
